version: 1

formatters:
  json_formatter:
    format: '{"timestamp": "%(asctime)s", "module": "%(module)s", "line_number": "%(lineno)d", "log_level": "%(levelname)s", "message": "%(message)s"}'


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json_formatter
    stream: ext://sys.stdout

loggers:
  dev:
    level: DEBUG
    handlers: [ console ]
    propagate: no


root:
  level: DEBUG
  handlers: [ console ]
